version: "3.3"

services:
  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "deutsch-bot"
    env_file:
      env_file
    #restart: "always"
    volumes:
      - ./:/app
